# Generated by Django 4.0.5 on 2023-08-03 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager_order', '0002_status_created_at_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='brief',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
