# Generated by Django 4.0.5 on 2023-08-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_order', '0003_status_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='brief',
        ),
    ]
