# Generated by Django 4.0.5 on 2023-08-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=1)),
                ('distance', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON'), (2, 'Starting'), (3, 'Pending'), (4, 'shutting off')], default=0)),
                ('battery', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, unique=True)),
                ('brief', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON'), (2, 'Starting'), (3, 'Pending'), (4, 'shutting off')], default=0)),
                ('battery', models.IntegerField(default=0)),
            ],
        ),
    ]
