# Generated by Django 4.0.5 on 2023-08-11 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_history',
        ),
        migrations.AlterField(
            model_name='orderhistorystatus',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.orderstatus'),
        ),
    ]
