# Generated by Django 4.0.5 on 2023-08-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_history',
            field=models.ManyToManyField(default=1, related_name='status_history', to='demo.orderstatus'),
        ),
    ]
