# Generated by Django 4.0.5 on 2023-08-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemhistory',
            name='brief',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='systemhistory',
            name='command',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
