# Generated by Django 4.0.5 on 2023-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_drone_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='distance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='drone',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
