# Generated by Django 4.0.5 on 2023-08-07 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_order_status_alter_order_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.orderstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_history',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='status_history', to='demo.orderstatus'),
        ),
    ]
