# Generated by Django 4.0.5 on 2023-08-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_dronetest_alter_drone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='describe',
        ),
    ]
