# Generated by Django 4.0.5 on 2023-08-08 22:32

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_order_status_alter_order_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='departure_address',
            field=models.CharField(default='36039 Pizarro dr, Fremont, Ca, 94653', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_history',
            field=models.ManyToManyField(default=demo.models.get_default_status, related_name='status_history', to='demo.orderstatus'),
        ),
    ]
