# Generated by Django 4.0.5 on 2023-08-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_order_departure_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_history',
            field=models.ManyToManyField(blank=True, null=True, related_name='status_history', to='demo.orderstatus'),
        ),
    ]
